# Generated by Django 2.2.5 on 2019-09-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('year_published', models.PositiveSmallIntegerField()),
                ('plot_summary', models.TextField()),
                ('cover', models.ImageField(upload_to='book_covers/')),
                ('genre', models.CharField(max_length=30)),
            ],
        ),
    ]
