# Generated by Django 2.2.5 on 2019-09-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('adventure', 'Adventure'), ('drama', 'Drama'), ('fantasy', 'Fantasy'), ('history', 'History'), ('graphic novel', 'Graphic Novel'), ('horror', 'Horror'), ('mystery', 'Mystery'), ('romance', 'Romance'), ('science fiction', 'Science Fiction'), ('thriller', 'Thriller'), ('young adult', 'Young Adult')], max_length=30),
        ),
    ]
